name: Build and deploy WebJob to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Create WebJob folder structure
        run: |
          mkdir -p webjob_package/App_Data/jobs/triggered/Action1
          echo "Creating webjob folder structure..."

      - name: Copy files to WebJob folder
        run: |
          echo "Copying published files to webjob package..."
          Copy-Item -Path publish/* -Destination webjob_package/App_Data/jobs/triggered/Action1 -Recurse
          Copy-Item -Path App_Data/jobs/triggered/Action1/settings.job -Destination webjob_package/App_Data/jobs/triggered/Action1
          
      - name: Debug Folder Structure
        run: |
          echo "Listing contents of webjob_package"
          Get-ChildItem -Path ./webjob_package -Recurse

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webjob
          path: webjob_package

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webjob

      - name: Debug Downloaded Artifact
        run: |
          echo "Listing contents of downloaded artifact"
          Get-ChildItem -Path ./webjob_package -Recurse

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'consolewebjob'  # Replace with your actual app name
          slot-name: 'Production'
          package: './webjob_package'  # Ensure the correct path to the package
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0604EEDA0594448E8ECF6AF869037A11 }}
