name: Build and deploy WebJob to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Prepare WebJob folder structure
        run: |
          mkdir webjob_package
          mkdir webjob_package/App_Data/jobs/triggered/Action1
          copy .\publish\* webjob_package\App_Data\jobs\triggered\Action1\
          copy .\App_Data\jobs\triggered\Action1\settings.job webjob_package\App_Data\jobs\triggered\Action1\
          echo ConsoleApp1.exe > webjob_package\App_Data\jobs\triggered\Action1\run.cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webjob
          path: webjob_package

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webjob
          path: webjob_package

      - name: List contents (for debugging)
        run: dir webjob_package /s

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'consolewebjob' # Replace with your actual Azure Web App name
          slot-name: 'Production'
          package: webjob_package
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0604EEDA0594448E8ECF6AF869037A11 }}
