name: Build and deploy Azure WebJob

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish WebJob project
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webjob-publish
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webjob-publish

      - name: Prepare WebJob structure
        shell: pwsh
        run: |
          # Create WebJob folder structure
          New-Item -ItemType Directory -Force -Path webjob_package/App_Data/jobs/triggered/Action1

          # Copy published files into WebJob folder
          Copy-Item -Path ./* -Recurse -Destination webjob_package/App_Data/jobs/triggered/Action1/

          # Create settings.job file with custom environment variables
          $settings = @'
          {
            "is_singleton": false,
            "schedule": "0 1 * * *",
            "environment_variables": {
              "APP_PROFILE": "Action1Folder",
              "DRY_RUN": "true"
            }
          }
          '@
          Set-Content -Path webjob_package/App_Data/jobs/triggered/Action1/settings.job -Value $settings -Encoding utf8NoBOM

      - name: Zip WebJob folder
        run: Compress-Archive -Path webjob_package/* -DestinationPath WebJob.zip

      - name: Deploy WebJob to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'consolewebjob' # Replace with your actual Azure App name
          slot-name: 'Production'
          package: WebJob.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0604EEDA0594448E8ECF6AF869037A11 }}
