name: Build and Deploy Azure WebJob

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish WebJob
        run: dotnet publish -c Release -o webjob-publish

      - name: Prepare WebJob package
        shell: pwsh
        run: |
          # Create WebJob folder structure
          New-Item -ItemType Directory -Force -Path webjob_package/App_Data/jobs/triggered/Action1

          # Copy published app files
          Copy-Item -Path webjob-publish/* -Recurse -Destination webjob_package/App_Data/jobs/triggered/Action1/

          # Create settings.job file with custom environment variables
          $settings = @'
          {
            "is_singleton": false,
            "schedule": "0 1 * * *",
            "environment_variables": {
              "APP_PROFILE": "Action1Folder",
              "DRY_RUN": "true"
            }
          }
          '@
          Set-Content -Path webjob_package/App_Data/jobs/triggered/Action1/settings.job -Value $settings -Encoding utf8NoBOM

      - name: Zip WebJob package
        run: Compress-Archive -Path webjob_package/* -DestinationPath webjob.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'consolewebjob'  # Replace with your actual app name
          package: webjob.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0604EEDA0594448E8ECF6AF869037A11 }}
